spring:
  datasource:
    platform: h2
  thymeleaf:
    cache: false
  h2:
    console:
      enable: true
      path: /h2

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

security:
  redirect:
    expose:
      attributes: true

debug: true